### ISSUE TITLE
CEC-client capability

### ISSUE THREAD

**Issue by masonbesmer** [JosefJantzen/MMM-AlexaControl#23]
Please add cec-client capability to the monitor toggle thing!

**Comment by JosefJantzen** [comment]
Hi, I added the cec-client but I'm not sure if it works because the library doesn't work for me. Can you test it? You can use it if you set vcgencmd to cec-client like this: `vcgencmd: "cec-client`. It uses the following commands: <br> `echo 'standby 0' | cec-client -s -d 1` and `echo 'on 0' | cec-client -s -d 1`. Before you can test it you have to update my module. For that navigate in it's folder and run `git pull`.

**Comment by masonbesmer** [comment]
Hello, I will submit a pullrequest of the way I implemented CEC compatibility using cec-client!

edit: 
[code added to node helper in the toggle section](https://pastebin.com/FhUbwmDK)

would be smart to add a config option for the standby/on addresses, so if the user has multiple monitors set up for some reason, or if the IP isn't the same, the user can overwrite the default config (which would be set to 0.0.0.0)

**Comment by JosefJantzen** [comment]
I added the edit of you. Tomorrow I will add the address option.

**Comment by JosefJantzen** [comment]
Now I added the cecAddress option. Could you please test it?

**Comment by masonbesmer** [comment]
Works good, thank you!
