### ISSUE TITLE
Custom device unresponsive

### ISSUE THREAD

**Issue by masonbesmer** [JosefJantzen/MMM-AlexaControl#24]
Hello! My custom device is detected in the Alexa App, however, when I try to turn it off/on it is unresponsive. What can I do to fix this?

https://pastebin.com/jmpadPwV

**Comment by JosefJantzen** [comment]
Hi, I think the problem is that `exec` is undefined. In the last days I added [Command devices](https://github.com/JoChef2/MMM-AlexaControl#command-device). They work like the notification devices.  Your device looks like that:
````js
commands: [
    {
        name: 'Media Center',
        port: 11105,
        OnOff: true,
        command: ["kodi &", `kodi-send --action='Quit'`]
    }
]
````
***Note:*** You have to update the module first with `git pull` in the module folder.
