### ISSUE TITLE
Only use with Echo Dot

### ISSUE THREAD

**Issue by axel-lung** [JosefJantzen/MMM-AlexaControl#42]
Hi!

Can we use AlexaControl Module with Alexa Module or I must have a Echo Dot from Amazon to use this module?

Thanks for your answer!

**Comment by JosefJantzen** [comment]
Hi! 
I never tested it with a Alexa module. If you have a module installed yet it will not take much time to test it. You only have to install the module and copy the sample config. But I think there is a big chance that it doesn't work because I think Alexa doesn't search for devices on it's own device (localhost). If you test it please post your result.

**Comment by axel-lung** [comment]
AlexaControl uses Alexa so if I setup Alexa on my Raspberry and not the module, maybe I can connect AlexaControl with alexa that I installed. What do you think about that?

**Comment by JosefJantzen** [comment]
I understood what you would like to do, but I never tested that. I don't know if it could work, but I think the easiest way is to try it. The problem I see is that Alexa searches in your whole Network for new devices, but I'm not sure if it can discover some on its own device because the devices will have the same IP as your Alexa. Maybe also it only works then you have discovered them with another devices and then you can only use them on your mirror. I don't have an external microphone to test it with my mirror so give it a try if you want.
