### ISSUE TITLE
Conflict with MMM-Screencast

### ISSUE THREAD

**Issue by Dresch360** [JosefJantzen/MMM-AlexaControl#46]
Does not load/work when MMM-Screencast is loaded. Is there any workaround or fix for this?

Thanks!

**Comment by JosefJantzen** [comment]
Hi, I think there isn't a solution because I'm pretty sure that the problem is like #35. MMM-Screencast also uses the Port 1900 that's also necessary for the discovery of the devices. Maybe a workaround is to discover all your devices without the Screencast module and then remove the code part in the node module node_fauxmo there the port is used to discover the devices. But I never tested that and it's not very practical. Sorry.

**Comment by Dresch360** [comment]
Thank you very much for your quick response! I did more digging and it looks like Port 1900 is a dedicated port used by Electron, Spotify, and MMM-Screencast. It also looks like port 1900 cannot be changed. I guess, this would need to be a tradeoff between using MMM-Screencast or MMM-AlexaControl. 
Thanks again for your reply and help.
