### ISSUE TITLE
notification and payload

### ISSUE THREAD

**Issue by ion46750** [JosefJantzen/MMM-AlexaControl#7]
hello, i have a problem with how to replace notification and payload.

i have tried many combinations but i don't know how to replace them.
this is the actual module config:

```
{
        		module: 'MMM-AlexaControl',
        		notifications: [
			    {
			        name: 'MMM-NowPlayingOnSpotify',
			        port: 11001,
			        OnOff: true,
			        notification: [["NOTIFICATION ON",{ action: "SHOW", module: "MMM-NowPlayingOnSpotify" }],["NOTIFICATION OFF",{ action: "HIDE", module: "MMM-NowPlayingOnSpotify" }]]
			    }
		],
			position: 'middle_center',
        		config:{
            			image: 
   			        pm2ProcessName: "mm",
            			vcgencmd: true
			}
		},
```

ok , so the mirror works ,but alexa is only finding pm2 processes ,mirror refresh and monitor power, but can't find the module to turn it on and off, for example i want to control MMM-NowPlayingOnSpotify module.

The name ,port and OnOff seems to be ok ,but the notification is the problem i think.

I changed the NOTIFICATION and PAYLOAD as i thinked.

Can you explain me how to change them?

`notification: [["NOTIFICATION ON", "PAYLOAD"],["NOTIFICATION OFF", "PAYLOAD"]]`

To be more explicied ,this part.

**Comment by JosefJantzen** [comment]
Hi, first you need to put the notifications array inside the config, too. Then you have to change the port because on this port is one of the configured devices. You should take `11100`. I think you want to send the notification to [MMM-RemoteControl](https://github.com/Jopyth/MMM-Remote-Control) ? The payloads are right but you have to edit also the notifications. I mean with `NOTIFICATION ON` and `NOTIFICATION OFF` the different notifications. You have to change both to `REMOTE_ACTION` so the MMM-RemoteControl module get the notifications. Here is the edit config:
```
{
        module: 'MMM-AlexaControl',
	position: 'middle_center',
        config:{
            	image: true,
   	        pm2ProcessName: "mm",
            	vcgencmd: true,
                notifications: [
	               {
			     name: 'MMM-NowPlayingOnSpotify',
			     port: 11101,
			     OnOff: true,
			     notification: [["REMOTE_ACTION",{ action: "SHOW", module: "MMM-NowPlayingOnSpotify" }],["REMOTE_ACTION",{ action: "HIDE", module: "MMM-NowPlayingOnSpotify" }]]
		      }
		],
	}
},
```
In addition you should configure the option `image`. I change it to `true` but if you don't want the image you can change it to `false`.
Do you really want to name the device `MMM-NowPlayingOnSpotify` because it's really long to say?
I hope it works and I will add a better explanation in the next days.

**Comment by ion46750** [comment]
First time ,I put the notifications in the config part ,and the magic mirror will say the config file is corrupted and it will indicate me the "notifications" part as it doesn't have to be there .

**Comment by JosefJantzen** [comment]
Have you test my edit config because it must be inside the config part? I think either you forgot a comma or the image option wasn't configured.

**Comment by ion46750** [comment]
I will try it soon as I will have my RPI on my hands. I will tell you if it works or not

**Comment by ion46750** [comment]
ok , with the spotify module ,it works somehow , but only with this , i copied tje same code for another modules , and only changed the name ,but alexa can't find them

**Comment by JosefJantzen** [comment]
You have to change the port also because every devices need another port. So you have use the port 11100 for Spotify. For the next module you should use 11101 and then for the next 11102.
